FluxLiveWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FluxLiveWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FluxLiveWebApp/Pages/Events/ClientEvents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluxLiveWebApp.Pages.Events
{
    public class ClientEventsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FluxLiveWebApp/Pages/Events/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxLive.Core;
using FluxLIve.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluxLiveWebApp.Pages.Events
{
    public class DeleteModel : PageModel
    {
        private readonly IEventData _eventData;
        public FluxEvent FluxEvent { get; set; } 
        public DeleteModel(IEventData eventData)
        {
            _eventData = eventData;
        }
        public async Task<IActionResult> OnGet(int eventId)
        {
            FluxEvent = _eventData.GetFluxEventById(eventId);
            if (FluxEvent == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int eventId)
        {
            var evt = _eventData.Delete(eventId);
            _eventData.Commit();

            if(evt == null)
            {
                return RedirectToPage("./NotFound");
            }

            TempData["Message"] = $"{evt.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

FluxLiveWebApp/Pages/Events/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxLive.Core;
using FluxLIve.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluxLiveWebApp.Pages.Events
{
    public class DetailModel : PageModel
    {
        public FluxEvent FluxEvent {get; set;}
        public IEventData _eventData;
        public DetailModel(IEventData eventData)
        {
            _eventData = eventData;
        }
        public IActionResult OnGet(int eventId)
        {
            FluxEvent = _eventData.GetFluxEventById(eventId);
            if (FluxEvent == null )
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

FluxLiveWebApp/Pages/Events/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxLive.Core;
using FluxLIve.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FluxLiveWebApp.Pages.Events
{
    public class EditModel : PageModel
    {
        private readonly IEventData _eventData;
        private readonly IHtmlHelper _htmlHelper;

       
        public IEnumerable<SelectListItem> EventItems { get; set; }
        [BindProperty]
        public FluxEvent FluxEvent { get; set; }
        public EventTypes EventTypes { get; set; }


        public EditModel(IEventData eventData,
                         IHtmlHelper htmlHelper)
        {
            _eventData = eventData;
            _htmlHelper = htmlHelper;

        }
        public IActionResult OnGet(int? eventId)
        {
            EventItems = _htmlHelper.GetEnumSelectList<EventTypes>();
            if (eventId.HasValue)
            {
                FluxEvent = _eventData.GetFluxEventById(eventId.Value);
            }
            else
            {
                FluxEvent = new FluxEvent();
            }
            if(FluxEvent == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                EventItems = _htmlHelper.GetEnumSelectList<EventTypes>();
                return Page();
            }
            if(FluxEvent.EventId > 0)
            {
                _eventData.Update(FluxEvent);
            }
            else
            {
                _eventData.Add(FluxEvent);                                                                                               
            }
            _eventData.Commit();
            return RedirectToPage("./Detail", new { eventId = FluxEvent.EventId });

        }
    }
}

FluxLiveWebApp/Pages/Events/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxLive.Core;
using FluxLIve.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluxLiveWebApp.Pages.Events
{
    public class ListModel : PageModel
    {
        private readonly IEventData _eventData;

        public String Message { get; set; }
        public IEnumerable<FluxEvent> EventDatas { get; set; }
       
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public ListModel(IEventData eventData)
        {
            _eventData = eventData;
        }
        public void OnGet()
        {
            Message = "hello world1";
            EventDatas = _eventData.GetFluxEventByName(SearchTerm);
        }


    }
}

FluxLiveWebApp/Pages/Events/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluxLiveWebApp.Pages.Events
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FluxLiveWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluxLiveWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

FluxLiveWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluxLiveWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

FluxLiveWebApp/ViewComponents/EventCountViewComponent.cs
using FluxLIve.data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluxLiveWebApp.ViewComponents
{
    public class EventCountViewComponent : ViewComponent
    {

        private readonly IEventData _eventData1;
        public EventCountViewComponent(IEventData eventData)
        {
            _eventData1 = eventData;
        }

        public IViewComponentResult Invoke()
        {
            var count = _eventData1.GetCountOfEvents();
            return View(count);
        }
    }
}

FluxLiveWebApp/Pages/Events/ClientEvents.cshtml
@page
@model FluxLiveWebApp.Pages.Events.ClientEventsModel
@{
}



@section Scripts {
    <script>
        $(function () {
            $.ajax("/api/events/",
                { method: "get" })
                .then(function (response) {
                    console.dir(response)
            }
        );
    </script>
}

FluxLiveWebApp/Pages/Events/Delete.cshtml
@page "{eventId}"
@model FluxLiveWebApp.Pages.Events.DeleteModel
@{
    
}



    <h2>Delete</h2>
    <div class="alert alert-danger">
        Are you sure you want to delete @Model.FluxEvent.Name ?
    </div>
    <form  method="post">
        <button type ="submit" class="btn btn-danger"> Yes!</button>
        <a class="btn btn-default" asp-page="List">Cancel</a>
    </form>

FluxLiveWebApp/Pages/Events/Detail.cshtml
@page
@model FluxLiveWebApp.Pages.Events.DetailModel
@{
}

<h2>   @Model.FluxEvent.Name </h2>

<div>
    ID: @Model.FluxEvent.EventId
</div>

<div>
    Description: @Model.FluxEvent.Description
</div>

<a asp-page="./List" class="btn btn-default">All Events</a>

FluxLiveWebApp/Pages/Events/Edit.cshtml
@page "{eventId:int?}"
@model FluxLiveWebApp.Pages.Events.EditModel
@{
}


<h2>   Editng @Model.FluxEvent.Name </h2>

<form  method="post">

    <input type="hidden" asp-for="FluxEvent.EventId" />
    <div class="form-group">
        <label asp-for="FluxEvent.Name"></label>
        <input class="form-control" asp-for="FluxEvent.Name" />
        <span class="text-danger" asp-validation-for="FluxEvent.Name">  </span>
    </div>
    <div class="form-group">
        <label asp-for="FluxEvent.Description"></label>
        <input class="form-control" asp-for="FluxEvent.Description" />
    </div>
    <div class="form-group">
        <label asp-for="FluxEvent.EventTypes"></label>
        <select class="form-control" 
                 asp-for="FluxEvent.EventTypes"
                asp-items="Model.EventItems">
            <option value="value">text</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{
                <partial name="_ValidationScriptsPartial" />
            }

FluxLiveWebApp/Pages/Events/List.cshtml
@page

@model ListModel
@{
    ViewData["Name"] = "List of data";
}


<h2>Events</h2>
<hr />

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input placeholder="...start typing search" type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphyicon glyphyicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>


@foreach (var fluxEvent in Model.EventDatas)
{
    <partial name="_Summary" model="fluxEvent" />
}
<a asp-page="./Edit" class="btn btn-primary">Create New</a>



@*@section footer {
    <div>@Model.Message</div>
}*@

FluxLiveWebApp/Pages/Events/NotFound.cshtml
@page
@model FluxLiveWebApp.Pages.Events.NotFoundModel
@{
}


<h3>    Your Event was not found.  </h3>
<a class="btn btn-primary" asp-page="./List">See all Events</a>

FluxLiveWebApp/Pages/Events/_Summary.cshtml
@using FluxLive.Core
@model FluxEvent

    <div class="card ">
        <div class="card-header">
            <h3>@Model.Name</h3>
        </div>
        <div class="card-body">
            <span>Description: @Model.Description</span>
        </div>
        <div class="card-footer">
            <a class="btn btn-lg"
               asp-page="./Detail" asp-route-EventId="@Model.EventId">
                <i class="glyphyicon glyphyicon-zoom-in"></i>
                view
            </a>
            <a class="btn btn-lg"
               asp-page="./Edit" asp-route-EventId="@Model.EventId">
                <i class="glyphyicon glyphyicon-edit"></i>
                edit
            </a>
            <a class="btn btn-lg"
               asp-page="./Delete" asp-route-EventId="@Model.EventId">
                <i class="glyphyicon glyphyicon-trash"></i>
                delete
            </a>
        </div>

    </div>

FluxLiveWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FluxLiveWebApp/Pages/Shared/Components/EventCount/Default.cshtml
@model int 

    <div class="well">
        There are @Model here. <a asp-page="/Events/List"> See the full list.</a> 
    </div> 

FluxLiveWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FluxLiveWebApp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">FluxLiveWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Events/List">Upcoming Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <vc:event-count></vc:event-count>
            @RenderSection("footer", required: false)
            &copy; 2021 - FluxLiveWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://use.fontawesome.com/863fccd9af.js"></script>
    <script src="https://use.fontawesome.com/dc6fffcf10.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>